# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build DB
      run: docker-compose build

    - name: Create DB
      run: docker-compose up -d

    - name: Test
      run: go test -v main_test.go

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Build
      run: go build -v main.go

  docker-bench-security:
    needs: build  
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Docker Bench Security
        run: |
           apt update
           apt intall curl
      - name: Download Docker Bench Security
        run: |
          curl -L https://raw.githubusercontent.com/docker/docker-bench-security/master/docker-bench-security.sh -o docker-bench-security.sh      
      - name: Run Docker Bench Security
        run: |
          docker-bench-security --recursive
          
